### ISSUE TITLE
TypeError: Invalid file: 45.0 (large error)

### ISSUE THREAD

**Issue by Jiraxys** [lucidrains/audiolm-pytorch#114]
Hello, when running app.py, i get a huge error, im not sure how to fix it.

FutureWarning: Pass size=1024 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  fft_window = librosa.util.pad_center(fft_window, n_fft)
C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Caching examples at: 'C:\Users\anedi\Desktop\audioldm\AudioLDM\gradio_cached_examples\15\log.csv'
Traceback (most recent call last):
  File "c:/Users/anedi/Desktop/audioldm/AudioLDM/app.py", line 286, in <module>
    gr.Examples(
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\helpers.py", line 69, in create_examples
    utils.synchronize_async(examples_obj.create)
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\utils.py", line 377, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\fsspec\asyn.py", line 99, in sync       
    raise return_result
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\fsspec\asyn.py", line 54, in _runner    
    result[0] = await coro
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\helpers.py", line 273, in create 
    await self.cache()
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\helpers.py", line 308, in cache  
    prediction = await Context.root_block.process_api(
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 937, 
in run_sync_in_worker_thread
    return await future
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 867, 
in run
    result = context.run(func, *args)
  File "c:/Users/anedi/Desktop/audioldm/AudioLDM/app.py", line 30, in text2audio
    waveform = text_to_audio(
  File "c:\Users\anedi\Desktop\audioldm\AudioLDM\audioldm\pipeline.py", line 115, in text_to_audio
    waveform = read_wav_file(original_audio_file_path, int(duration * 102.4) * 160)
  File "c:\Users\anedi\Desktop\audioldm\AudioLDM\audioldm\audio\tools.py", line 55, in read_wav_file
    waveform, sr = torchaudio.load(filename)  # Faster!!!
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\torchaudio\backend\soundfile_backend.py", line 205, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 655, in __init__    
    self._file = self._open(file, mode_int, closefd)
  File "C:\Users\anedi\AppData\Local\Programs\Python\Python38\lib\site-packages\soundfile.py", line 1209, in _open      
    raise TypeError("Invalid file: {0!r}".format(self.name))
TypeError: Invalid file: 45.0

**Comment by lucidrains** [comment]
wrong repo
