### ISSUE TITLE
Training SemanticTransformer with accelerate

### ISSUE THREAD

**Issue by stevenhillis** [lucidrains/audiolm-pytorch#152]
When I try to train the semantic transformer with accelerate (`accelerate launch train_semantic.py`, where train_semantic.py is lifted directly from the readme), I get 

> Traceback (most recent call last):
  File "/big/users/steven-hillis/code/tts/audiolm-pytorch/train_semantic.py", line 45, in <module>
    main()
  File "/big/users/steven-hillis/code/tts/audiolm-pytorch/train_semantic.py", line 22, in main
  File "/big/users/steven-hillis/code/tts/audiolm-pytorch/audiolm_pytorch/trainer.py", line 638, in __init__
    trainer = SemanticTransformerTrainer(
  File "<@beartype(audiolm_pytorch.trainer.SemanticTransformerTrainer.__init__) at 0x7f3eeda18160>", line 148, in __init__
    ) = self.accelerator.prepare(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1122, in prepare
      File "/big/users/steven-hillis/code/tts/audiolm-pytorch/audiolm_pytorch/trainer.py", line 638, in __init__
result = tuple(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1123, in <genexpr>
    ) = self.accelerator.prepare(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1122, in prepare
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 977, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1202, in prepare_model
    result = tuple(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1123, in <genexpr>
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 657, in __init__
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 977, in _prepare_one
    _sync_module_states(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/distributed/utils.py", line 136, in _sync_module_states
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/accelerate/accelerator.py", line 1202, in prepare_model
    _sync_params_and_buffers(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/distributed/utils.py", line 154, in _sync_params_and_buffers
    dist._broadcast_coalesced(
RuntimeError: The size of tensor a (64) must match the size of tensor b (0) at non-singleton dimension 2
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 657, in __init__
    _sync_module_states(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/distributed/utils.py", line 136, in _sync_module_states
    _sync_params_and_buffers(
  File "/home/users/steven-hillis/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/distributed/utils.py", line 154, in _sync_params_and_buffers
    dist._broadcast_coalesced(

My accelerate config is okay, since it works for training soundstream model. I also get no errors when I run `python train_semantic.py` for single-gpu training. There's a specific problem with accelerate preparing the SemanticTransformer model.

**Comment by lucidrains** [comment]
are you using hubert?

**Comment by stevenhillis** [comment]
Yes, hubert.

```
from audiolm_pytorch import HubertWithKmeans, SemanticTransformer, SemanticTransformerTrainer

wav2vec = HubertWithKmeans(
    checkpoint_path = './hubert/hubert_base_ls960.pt',
    kmeans_path = './hubert/hubert_base_ls960_L9_km500.bin'
)

semantic_transformer = SemanticTransformer(
    num_semantic_tokens = wav2vec.codebook_size,
    dim = 1024,
    depth = 6,
    # has_condition = True,               # this will have to be set to True
    # cond_as_self_attn_prefix = True     # whether to condition as prefix to self attention, instead of cross attention, as was done in 'VALL-E' paper
).cuda()

trainer = SemanticTransformerTrainer(
    transformer = semantic_transformer,
    wav2vec = wav2vec,
    paths_list_path = '/path/to/training/manifest.txt',
    batch_size = 256,
    grad_accum_every = 1,
    dl_num_workers = 8,
    data_max_length_seconds = 2,
    num_train_steps = 1_000_000,
    force_clear_prev_results = True,
    accelerate_kwargs = {'log_with': 'wandb', 'project_dir': "./runs"},
    results_folder='./results/semantic/'
)

trainer.train()
```

**Comment by lucidrains** [comment]
@stevenhillis deepgram is doing generative models now? i thought they were just speech to text?

**Comment by stevenhillis** [comment]
I chased down the fairseq model idea a little, and I don't think that's it. The pretrained huberts are on huggingface too, and I can get an embed of the right size from theirs with 

 ```
# hidden_states return object contains embedding output, followed by outputs of each layer
AutoModel.from_pretrained("facebook/hubert-base-ls960").eval()(inputs, output_hidden_states=True).hidden_states[output_layer + 1]
```
It doesn't match the output of the fairseq implementation (although those outputs are themselves quite nondeterministic), but more importantly, I get the same error accelerating train_semantic.py with the huggingface hubert as with the fairseq. 

Moreover, I also get the same error when trying to launch a train_fine.py script with accelerate.

**Comment by lucidrains** [comment]
> Transcription is still the core product offering, but the market is ready for more! We'll be doing a bunch of work on generative modeling for speech and text this year. [Always hiring researchers!](https://jobs.lever.co/deepgram/84ef78eb-d03e-4262-96f3-8f7262cd1ab7?lever-via=S65miIFKCM)

I'm good thanks. ok will look into it later this weekend

**Comment by lzl1456** [comment]
oh Pity ！ I extracted the token in advance,so I don't need to import the hubert model 。 but But still this problem occurs
when use accelerate launch multi-GPu  train SemanticTransformer  
![image](https://user-images.githubusercontent.com/38452732/230896615-a1e55820-2435-4e8d-b697-aaf8cc3aa44d.png)

do you have a plan to fix this @lucidrains   @stevenhillis

**Comment by lzl1456** [comment]
I think I solved the problem

the class Attention(nn.Module):   
add code

if num_null_kv > 0:
            self.null_kv = nn.Parameter(torch.randn(2, num_null_kv, dim_head))

**Comment by Hit1ron** [comment]
oh i see, the parameter shuffle of the dataloader needs to be False
