### ISSUE TITLE
Question: Are there any work arounds for using DeepSpeed for multi-gpu training

### ISSUE THREAD

**Issue by rgxb2807** [lucidrains/audiolm-pytorch#240]
Hi, thanks so much for the incredible repo.  

I've been able to successfully train using a multi-gpu setup and accelerate.  I'm wondering if it's possible to use Microsoft's DeepSpeed with the accelerate library.  

When I enable Stage 1 or Stage 2 in the accelerate configuration I get the following error.  Any ideas for workarounds? 

```
Traceback (most recent call last):
  File "/audio/soundstream_train.py", line 43, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/trainer.py", line 572, in train
    logs = self.train_step()
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/trainer.py", line 441, in train_step
    loss, (recon_loss, multi_spectral_recon_loss, adversarial_loss, feature_loss, all_commitment_loss) = self.soundstream(wave, return_loss_breakdown = True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1769, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 852, in forward
    (stft_real_logits, stft_real_intermediates), (stft_fake_logits, stft_fake_intermediates) = map(partial(self.stft_discriminator, return_intermediates=True), (real, fake))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 285, in forward
    x = layer(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 308, in forward
    return self.fn(x, **kwargs) + x
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 197, in forward
    weight, bias = map(torch.view_as_complex, (self.weight, self.bias))
RuntimeError: Tensor must have a storage_offset divisible by 2
Traceback (most recent call last):
  File "/audio/soundstream_train.py", line 43, in <module>
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/trainer.py", line 572, in train
    logs = self.train_step()
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/trainer.py", line 441, in train_step
    loss, (recon_loss, multi_spectral_recon_loss, adversarial_loss, feature_loss, all_commitment_loss) = self.soundstream(wave, return_loss_breakdown = True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 1769, in forward
    loss = self.module(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 852, in forward
    (stft_real_logits, stft_real_intermediates), (stft_fake_logits, stft_fake_intermediates) = map(partial(self.stft_discriminator, return_intermediates=True), (real, fake))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 285, in forward
    x = layer(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 308, in forward
    return self.fn(x, **kwargs) + x
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/audiolm_pytorch/soundstream.py", line 197, in forward
    weight, bias = map(torch.view_as_complex, (self.weight, self.bias))
RuntimeError: Tensor must have a storage_offset divisible by 2
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 440) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 926, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 671, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
soundstream_train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-18_22:04:28
  host      : c6e49f99abae
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 441)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-18_22:04:28
  host      : c6e49f99abae
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 440)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by lucidrains** [comment]
@rgxb2807 i was hoping accelerate would just work lol

**Comment by lucidrains** [comment]
@rgxb2807 maybe you can raise an issue at the accelerate repository

**Comment by rgxb2807** [comment]
> @rgxb2807 i was hoping accelerate would just work lol

It does! and I'm grateful for it. 

> @rgxb2807 maybe you can raise an issue at the accelerate repository

I'll do some digging and raise an issue where appropriate.

**Comment by rgxb2807** [comment]
Raised the issue with the accelerate team here [#2106](https://github.com/huggingface/accelerate/issues/2106)

**Comment by ShakyaAbeytunge** [comment]
Hi,

I tried both Deepspeed Stage 2 and 3, but I get some other error:

```powershell
Distributed environment: DEEPSPEED  Backend: nccl
Num processes: 3
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: fp16
ds_config: {'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 2, 'gradient_accumulation_steps': 8, 'zero_optimization': {'stage': 3, 'offload_optimizer': {'device': 'cpu', 'nvme_path': None}, 'offload_param': {'device': 'cpu', 'nvme_path': None}, 'stage3_gather_16bit_weights_on_model_save': False}, 'gradient_clipping': 'auto', 'steps_per_print': inf, 'fp16': {'enabled': True, 'auto_cast': True}, 'bf16': {'enabled': False}}

Distributed environment: DEEPSPEED  Backend: nccl
Num processes: 3
Process index: 1
Local process index: 1
Device: cuda:1

Mixed precision type: fp16
ds_config: {'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 2, 'gradient_accumulation_steps': 8, 'zero_optimization': {'stage': 3, 'offload_optimizer': {'device': 'cpu', 'nvme_path': None}, 'offload_param': {'device': 'cpu', 'nvme_path': None}, 'stage3_gather_16bit_weights_on_model_save': False}, 'gradient_clipping': 'auto', 'steps_per_print': inf, 'fp16': {'enabled': True, 'auto_cast': True}, 'bf16': {'enabled': False}}

Distributed environment: DEEPSPEED  Backend: nccl
Num processes: 3
Process index: 2
Local process index: 2
Device: cuda:2

Mixed precision type: fp16
ds_config: {'train_batch_size': 'auto', 'train_micro_batch_size_per_gpu': 2, 'gradient_accumulation_steps': 8, 'zero_optimization': {'stage': 3, 'offload_optimizer': {'device': 'cpu', 'nvme_path': None}, 'offload_param': {'device': 'cpu', 'nvme_path': None}, 'stage3_gather_16bit_weights_on_model_save': False}, 'gradient_clipping': 'auto', 'steps_per_print': inf, 'fp16': {'enabled': True, 'auto_cast': True}, 'bf16': {'enabled': False}}

training with dataset of 186068 samples and validating with randomly splitted 9794 samples
[rank2]: Traceback (most recent call last):
[rank2]:   File "/data/abeytunge/audiolm-pytorch/train_soundstream.py", line 28, in <module>
[rank2]:     trainer = SoundStreamTrainer(
[rank2]:   File "<@beartype(audiolm_pytorch.trainer.SoundStreamTrainer.__init__) at 0x7f7ace8c5820>", line 618, in __init__
[rank2]:   File "/data/abeytunge/audiolm-pytorch/audiolm_pytorch/trainer.py", line 398, in __init__
[rank2]:     ) = self.accelerator.prepare(
[rank2]:   File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 1387, in prepare
[rank2]:     raise AssertionError(
[rank2]: AssertionError: You can't use same `Accelerator()` instance with multiple models when using DeepSpeed
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data/abeytunge/audiolm-pytorch/train_soundstream.py", line 28, in <module>
[rank0]:     trainer = SoundStreamTrainer(
[rank0]:   File "<@beartype(audiolm_pytorch.trainer.SoundStreamTrainer.__init__) at 0x7f5872c9b820>", line 618, in __init__
[rank0]:   File "/data/abeytunge/audiolm-pytorch/audiolm_pytorch/trainer.py", line 398, in __init__
[rank0]:     ) = self.accelerator.prepare(
[rank0]:   File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 1387, in prepare
[rank0]:     raise AssertionError(
[rank0]: AssertionError: You can't use same `Accelerator()` instance with multiple models when using DeepSpeed
[rank1]: Traceback (most recent call last):
[rank1]:   File "/data/abeytunge/audiolm-pytorch/train_soundstream.py", line 28, in <module>
[rank1]:     trainer = SoundStreamTrainer(
[rank1]:   File "<@beartype(audiolm_pytorch.trainer.SoundStreamTrainer.__init__) at 0x7fe19f002820>", line 618, in __init__
[rank1]:   File "/data/abeytunge/audiolm-pytorch/audiolm_pytorch/trainer.py", line 398, in __init__
[rank1]:     ) = self.accelerator.prepare(
[rank1]:   File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/accelerator.py", line 1387, in prepare
[rank1]:     raise AssertionError(
[rank1]: AssertionError: You can't use same `Accelerator()` instance with multiple models when using DeepSpeed
[rank0]:[W730 17:25:52.113936539 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0730 17:25:53.492863 3083740 /net/home/u.misc/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3084011 closing signal SIGTERM
W0730 17:25:53.495597 3083740 /net/home/u.misc/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3084012 closing signal SIGTERM
E0730 17:25:53.665064 3083740 /net/home/u.misc/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3084010) of binary: /u/repmus/abeytunge/miniconda3/envs/py3.9/bin/python3.9
Traceback (most recent call last):
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1184, in launch_command
    deepspeed_launcher(args)
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/accelerate/commands/launch.py", line 868, in deepspeed_launcher
    distrib_run.run(args)
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/u/repmus/abeytunge/miniconda3/envs/py3.9/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_soundstream.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-30_17:25:53
  host      : reach1.ircam.fr
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3084010)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
``` 

Could anyone help with this?
