### ISSUE TITLE
Error in exporting soundstream to onnx

### ISSUE THREAD

**Issue by kalradivyanshu** [lucidrains/audiolm-pytorch#254]
Has anyone exported the soundstream model to ONNX? I tried:

`torch.onnx.export(soundstream, audio, "soundstream.onnx")`

but it fails with 

```
/home/divya/.local/lib/python3.8/site-packages/audiolm_pytorch/utils.py:11: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  seq_slice = slice(None, rounded_seq_len) if not from_left else slice(-rounded_seq_len, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<@beartype(torch.onnx.utils.export) at 0x7fb5d0936820>", line 369, in export
  File "/home/divya/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/divya/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "<@beartype(torch.onnx.utils._model_to_graph) at 0x7fb5d093e700>", line 11, in _model_to_graph
  File "/home/divya/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1011, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 915, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/divya/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 1285, in _get_trace_graph
    outs = ONNXTracedModule(
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 133, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/divya/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 124, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/audiolm_pytorch/soundstream.py", line 827, in forward
    x = self.encoder_attn(x)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/audiolm_pytorch/soundstream.py", line 436, in forward
    x = attn(x, attn_bias = attn_bias) + x
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/local_attention/transformer.py", line 106, in forward
    out = self.attn_fn(q, k, v, mask = mask, attn_bias = attn_bias)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/divya/.local/lib/python3.8/site-packages/local_attention/local_attention.py", line 126, in forward
    (needed_pad, q), (_, k), (_, v) = map(lambda t: pad_to_multiple(t, self.window_size, dim = -2), (q, k, v))
  File "/home/divya/.local/lib/python3.8/site-packages/local_attention/local_attention.py", line 126, in <lambda>
    (needed_pad, q), (_, k), (_, v) = map(lambda t: pad_to_multiple(t, self.window_size, dim = -2), (q, k, v))
  File "/home/divya/.local/lib/python3.8/site-packages/local_attention/local_attention.py", line 37, in pad_to_multiple
    if m.is_integer():
AttributeError: 'Tensor' object has no attribute 'is_integer'
```
Any help would be really appreciated, thanks!

**Comment by lucidrains** [comment]
@kalradivyanshu ahh darn... can't wait until Tri's flash attention cuda kernel is standard. it has windowed local attention built-in

**Comment by lucidrains** [comment]
> Update: the error goes away when `use_local_attn=False`, but I am guessing it will have adverse affect on the performance of the network?

some researchers have told me local attention does little, but i wouldn't bet against it

**Comment by lucidrains** [comment]
@kalradivyanshu maybe i can offer a full attention causal layer in there? with flash attention, 8k is nothing these days

**Comment by lucidrains** [comment]
@kalradivyanshu oh good to hear! would welcome a PR upstream, in the spirit of open source 🙏 

i don't really know, as i haven't been following the research there

**Comment by lucidrains** [comment]
@kalradivyanshu hmm, strange, `m` should never be a tensor

**Comment by lucidrains** [comment]
@kalradivyanshu is your converted onnx model working ok with this change?

**Comment by lucidrains** [comment]
@kalradivyanshu oh i see, ok yea let me know if the onnx model is ok

wow, you are using an unpublished feature! (residual FSQ)

does it work?

**Comment by lucidrains** [comment]
ahh, you haven't actually trained it yet, gotcha
