### ISSUE TITLE
SoundStream training hangs using accelerate launch and the use_finite_scalar_quantizer=True setting

### ISSUE THREAD

**Issue by ThomasLWang** [lucidrains/audiolm-pytorch#279]
### Issue Description:
When training SoundStream using accelerate launch with use_finite_scalar_quantizer=True, the process occasionally hangs in the following parts of the code:
Quantizer:
```
if not self.use_finite_scalar_quantizer:
    x, indices, commit_loss = self.rq(x)
else:
    x, indices = self.rq(x)
    commit_loss = self.zero
```
Loss Calculation:
```
target = default(target, orig_x)
recon_loss = F.mse_loss(target, recon_x)

# Multispectral reconstruction loss
multi_spectral_recon_loss = self.zero
if self.multi_spectral_recon_loss_weight > 0:
    for mel_transform, alpha in zip(self.mel_spec_transforms, self.mel_spec_recon_alphas):
        orig_mel, recon_mel = map(mel_transform, (orig_x, recon_x))
        log_orig_mel, log_recon_mel = map(log, (orig_mel, recon_mel))
        l1_mel_loss = (orig_mel - recon_mel).abs().sum(dim=-2).mean()
        l2_log_mel_loss = alpha * vector_norm(log_orig_mel - log_recon_mel, dim=-2).mean()
        multi_spectral_recon_loss = multi_spectral_recon_loss + l1_mel_loss + l2_log_mel_loss

# Adversarial loss calculation
adversarial_losses = []
discr_intermediates = []

real, fake = orig_x, recon_x
(stft_real_logits, stft_real_intermediates), (stft_fake_logits, stft_fake_intermediates) = map(
    partial(self.stft_discriminator, return_intermediates=True), (real, fake)
)
discr_intermediates.append((stft_real_intermediates, stft_fake_intermediates))

scaled_real, scaled_fake = real, fake
for discr, downsample in zip(self.discriminators, self.downsamples):
    scaled_real, scaled_fake = map(downsample, (scaled_real, scaled_fake))
    (real_logits, real_intermediates), (fake_logits, fake_intermediates) = map(
        partial(discr, return_intermediates=True), (scaled_real, scaled_fake)
    )
    discr_intermediates.append((real_intermediates, fake_intermediates))
    one_adversarial_loss = hinge_gen_loss(fake_logits)
    adversarial_losses.append(one_adversarial_loss)

feature_losses = []
for real_intermediates, fake_intermediates in discr_intermediates:
    losses = [F.l1_loss(real_intermediate, fake_intermediate)
              for real_intermediate, fake_intermediate in zip(real_intermediates, fake_intermediates)]
    feature_losses.extend(losses)

feature_loss = torch.stack(feature_losses).mean()
adversarial_losses.append(hinge_gen_loss(stft_fake_logits))
adversarial_loss = torch.stack(adversarial_losses).mean()
all_commitment_loss = commit_loss.sum()

total_loss = (
    recon_loss * self.recon_loss_weight +
    multi_spectral_recon_loss * self.multi_spectral_recon_loss_weight +
    adversarial_loss * self.adversarial_loss_weight +
    feature_loss * self.feature_loss_weight +
    all_commitment_loss
)
```

### Additional Information:
This issue does not occur when use_finite_scalar_quantizer=False.
Running the code directly in Python also avoids this issue.
Expected Behavior:
With use_finite_scalar_quantizer=True, the code should execute without hanging in either the quantizer or loss calculation sections.

### Environment:
AudioLM version: 2.1.0
torch version: 2.5.1
torchaudio version: 2.5.1
Python version: 3.10.15
accelerate version: 1.1.0
Accelerator setup: 8 GPUs, no mix precision

### Steps to Reproduce:
Set up a training script with use_finite_scalar_quantizer=True.
```
from audiolm_pytorch import SoundStream, SoundStreamTrainer
soundstream = SoundStream(
    codebook_size = 4096,
    rq_num_quantizers = 8,
    rq_groups = 2,                       # this paper proposes using multi-headed residual vector quantization - https://arxiv.org/abs/2305.02765
    use_lookup_free_quantizer = True,    # whether to use residual lookup free quantization - there are now reports of successful usage of this unpublished technique
    use_finite_scalar_quantizer = False, # whether to use residual finite scalar quantization
    attn_window_size = 128,              # local attention receptive field at bottleneck
    attn_depth = 2                       # 2 local attention transformer blocks - the soundstream folks were not experts with attention, so i took the liberty to add some. encodec went with lstms, but attention should be better
)

trainer = SoundStreamTrainer(
    soundstream,
    folder = '/path/to/audio/files',
    batch_size = 4,
    grad_accum_every = 8,         # effective batch size of 32
    data_max_length_seconds = 2,  # train on 2 second audio
    num_train_steps = 1_000_000
).cuda()

trainer.train()
```

Launch the training with accelerate launch.
Observe that the process hangs at the quantizer or during loss calculation.

### Potential Fix Ideas or Workarounds:
Currently, the only workarounds are to:
Set use_finite_scalar_quantizer=False.
Run the code directly in Python instead of using accelerate launch.

**Comment by lucidrains** [comment]
@ThomasLWang hey Thomas, thanks for raising this issue! could you let me know if the issue persists in v2.1.1?

otherwise curious what kind of results you get with residual FSQ! (although I think if you use the latest residual VQ with the new rotation trick from Stanford, it should work amazing too)

**Comment by gyohng** [comment]
(using the latest clone from git)

I'm using a multi-GPU instance from vast.ai, and accelerate launch always hangs for num_processes>=2 regardless of the other settings. I tried quite a few things - environment variables, different versions, patching code, even using Python 3.11 with all incompatible code commented out (just leaving soundstream). The training always hangs when started with accelerate launch.

I can run it in a single thread without `accelerate launch` without issues. 

After several minutes of hanging like this, it throws an error that says that the NCCL watchdog triggered after N seconds (something like 400 seconds), and then it exits without even training for a single epoch.

I tried a few environment variables - I think you had a few posts yourself, and then I went to other projects and checked what they had, to no avail. I could never make it train using multiple GPUs with `accelerate launch` no matter the configuration or the environment variables.


![image](https://github.com/user-attachments/assets/b7db5243-b3a9-4afa-9753-b60cea050b9f)


My code looks like this. I tried on multi-GPU boxes with 4090 and H100
```py
from audiolm_pytorch import SoundStream, SoundStreamTrainer                                                                         
                                                                                                                                    
if __name__=='__main__':                                                                                                            
  soundstream = SoundStream(                                                                                                        
    target_sample_hz = 48000,.                                                                                                      
    codebook_size = 4096,                                                                                                           
    rq_num_quantizers = 8,                                                                                                          
    rq_groups = 2,                       
    use_lookup_free_quantizer = True,
    use_finite_scalar_quantizer = False,
    attn_window_size = 128,             
    attn_depth = 2                      
  )                                                                                                                                   
                                                                                                                                    
  trainer = SoundStreamTrainer(                                                                                                     
    soundstream,                                                                                                                    
    folder = '/audioset-mp3',                                                                                                       
    batch_size = 2,                                                                                                                 
    grad_accum_every = 8,       
    data_max_length_seconds = 2, 
    num_train_steps = 1000000                                                                                                       
  ).cuda()                                                                                                                            
                                                                                                                                    
  trainer.train()                                           
```

**Comment by lucidrains** [comment]
@gyohng yes I see, does it work if you turn off `use_lookup_free_quantizer` ?

**Comment by gyohng** [comment]
yes, it goes ahead if I change this one to False.

**Comment by lucidrains** [comment]
@gyohng thanks George

what happens if you run `pip list | grep vector` in the terminal? curious which version you are on

**Comment by gyohng** [comment]
vector-quantize-pytorch      1.18.6

**Comment by lucidrains** [comment]
@gyohng ok thanks, I will try to fix it again tomorrow

**Comment by lucidrains** [comment]
@gyohng do you and Thomas work together? why is there a sudden surge of interest in this repo?

**Comment by ThomasLWang** [comment]
Thank you for your quick response. I'm currently testing v2.1.2, as I noticed that it was released after v2.1.1, so I decided to go straight to v2.1.2.
@gyohng and I don't know each other. I'm working on a project that requires training SoundStream from scratch. audiolm-pytorch project has been incredibly helpful, and I hope to contribute to it as well.
@gyohng, I also encountered the NCCL watchdog timeout error. I tried setting the timeout to a very high value, but even after waiting for several hours, there was no result.

**Comment by ThomasLWang** [comment]
I'm encountering a consistent RuntimeError when trying to train on 8 GPUs using accelerate launch with no mixed precision, on Audiolm-pytorch v2.1.2. I have tested two configurations, both resulting in the same error.

Configuration 1:
```
use_lookup_free_quantizer = False,
use_finite_scalar_quantizer = True,
finite_scalar_quantizer_levels = [7, 5, 5, 5, 5]
```
```
soundstream = SoundStream(
    rq_num_quantizers = 8,
    rq_groups = 2,
    use_lookup_free_quantizer = False,
    use_finite_scalar_quantizer = True,
    finite_scalar_quantizer_levels = [7, 5, 5, 5, 5],
    attn_window_size = 128,
    attn_depth = 2
).cuda()

trainer = SoundStreamTrainer(
    soundstream,
    folder = audio_folder,
    results_folder = results_folder,
    batch_size = 4,
    grad_accum_every = 8,
    data_max_length_seconds = 10,
    num_train_steps = 1_000_000,
    force_clear_prev_results=False
).cuda()

```
Configuration 2:
`use_lookup_free_quantizer = True,
use_finite_scalar_quantizer = False
`
`soundstream = SoundStream(
    codebook_size = 4096,
    rq_num_quantizers = 8,
    rq_groups = 2,
    use_lookup_free_quantizer = True,
    use_finite_scalar_quantizer = False,
    attn_window_size = 128,
    attn_depth = 2
).cuda()

trainer = SoundStreamTrainer(
    soundstream,
    folder = audio_folder,
    results_folder = results_folder,
    batch_size = 4,
    grad_accum_every = 8,
    data_max_length_seconds = 10,
    num_train_steps = 1_000_000,
    force_clear_prev_results=False
).cuda()
`

Error Message:
Both configurations produce the following error:

> [rank7]: Traceback (most recent call last):
[rank7]:   File "/home/tom/voicego/audiolm-pytorch/train_soundstream.py", line 30, in <module>
[rank7]:     trainer.train()
[rank7]:   File "/home/tom/voicego/audiolm-pytorch/audiolm_pytorch/trainer.py", line 709, in train
[rank7]:     logs = self.train_step()
[rank7]:   File "/home/tom/voicego/audiolm-pytorch/audiolm_pytorch/trainer.py", line 578, in train_step
[rank7]:     loss, (recon_loss, multi_spectral_recon_loss, adversarial_loss, feature_loss, all_commitment_loss) = self.soundstream(wave, return_loss_breakdown = True)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1643, in forward
[rank7]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1459, in _run_ddp_forward
[rank7]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/home/tom/voicego/audiolm-pytorch/audiolm_pytorch/soundstream.py", line 843, in forward
[rank7]:     x, indices = self.rq(x)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/vector_quantize_pytorch/residual_fsq.py", line 308, in forward
[rank7]:     rand_quantize_dropout_fixed_seed = get_maybe_sync_seed()
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/vector_quantize_pytorch/residual_fsq.py", line 43, in get_maybe_sync_seed
[rank7]:     dist.all_reduce(rand_int)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
[rank7]:     return func(*args, **kwargs)
[rank7]:   File "/home/tom/anaconda3/envs/audiolm/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
[rank7]:     work = group.allreduce([tensor], opts)
[rank7]: RuntimeError: No backend type associated with device type cpu

**Comment by lucidrains** [comment]
@ThomasLWang oops, want to try again with 2.1.4?

**Comment by ThomasLWang** [comment]
training with dataset of 2567 samples and validating with randomly splitted 136 samples

0: soundstream total loss: 21.566, soundstream recon loss: 0.010 | discr (scale 1) loss: 2.000 | discr (scale 0.5) loss: 2.000 | discr (scale 0.25) loss: 2.000
0: saving to /mnt/data/tomtrain/audiolm-pytorch/results


[rank6]:[E1108 19:03:44.372992501 ProcessGroupNCCL.cpp:616] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=977, OpType=BROADCAST, NumelIn=414297, NumelOut=414297, Timeout(ms)=1800000) ran for 1800039 milliseconds before timing out.

**Comment by ThomasLWang** [comment]
I tried audiolm-pytorch versions 2.1.4 and 2.2.1 with the following settings:
use_lookup_free_quantizer = True, use_finite_scalar_quantizer = False
use_lookup_free_quantizer = False, use_finite_scalar_quantizer = True
However, it only produces a training loss of 0 and then hangs. All 8 GPUs show Volatile GPU-Util at 100% with Power Usage/Cap at 70W / 300W.

```
training with dataset of 2567 samples and validating with randomly splitted 136 samples

0: soundstream total loss: 21.566, soundstream recon loss: 0.010 | discr (scale 1) loss: 2.000 | discr (scale 0.5) loss: 2.000 | discr (scale 0.25) loss: 2.000
0: saving to /mnt/data/tomtrain/audiolm-pytorch/results

[rank6]:[E1108 19:03:44.372992501 ProcessGroupNCCL.cpp:616] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=977, OpType=BROADCAST, NumelIn=414297, NumelOut=414297, Timeout(ms)=1800000) ran for 1800039 milliseconds before timing out.
```

**Comment by lucidrains** [comment]
@ThomasLWang ahh forgot to account for evaluation

want to try (hopefully last) time?

**Comment by lucidrains** [comment]
@ThomasLWang also, given you are so keen on getting residual FSQ working, you must be seeing a strong signal from this experimental architecture?

**Comment by gyohng** [comment]
@lucidrains I spun another instance on vast.ai with dual H100, and it's hanging in a different place (latest git) - regardless of those flags (both set to false or true). It's hanging in `accelerator.wait_for_everyone()` when trainer tries to save the flac file.

What I found out is that for two processes that accelerate starts - one keeps running through the entire function and exits the function (I added some debug prints to verify that), another one hangs in the `self.accelerator.wait_for_everyone()` call after the `{steps}: saving to {str....` conditional branch in `trainer.py` - I think the one that hangs is the one that actually doesn't go inside the branch.

To prevent the hang I removed `self.is_main` check for the flac saving branch and only added it around the actual file write - so both processes enter the condition and generate ema, etc, but only the `is_main` one calls `torchaudio.save`. I'm not familiar enough with the internals of `accelerate` to understand why this prevents the hang, and why the non-modified code hangs.

I don't know if it's related to the other report - it would hang only when it attempts to write the flac file during the 0th step. if I comment out flac writing, it still can successfully write the model checkpoint and doesn't hang.

**Comment by lucidrains** [comment]
@gyohng thank you George

do you mean [this line](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/trainer.py#L1588)?

**Comment by lucidrains** [comment]
@gyohng ohh, did you turn off the ema? (`use_ema = False`) ?

**Comment by gyohng** [comment]
No, did not turn the ema off.

This line (SoundStream trainer): 
https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/trainer.py#L693

**Comment by gyohng** [comment]
Just to clarify: the training code is the same as I pasted before in this issue. No hangs when started directly with python. Accelerate launch starts two processes (because there are two GPUs). It hangs in one of the processes at the wait_for_everyone line the point, L693, while the other process continues successfully and exits this function. If I disable the flac writing condition - the hang is gone. If I enable this condition regardless of is_main, so that both processes do the work (but only one saves the result), the hang is gone as well.

**Comment by lucidrains** [comment]
@gyohng let's just go with your solution for now and i'll figure out the root cause later

**Comment by lucidrains** [comment]
@gyohng yes, technically this is a different issue, but let's resolve it

**Comment by gyohng** [comment]
Thanks, I really appreciate. If you can't reproduce, I can add your SSH key to my vast.ai instance (no valuable info there, so can be completely wiped and reconfigured if necessary).

**Comment by lucidrains** [comment]
@gyohng thanks for the offer, i think it should be resolved in the latest version
