### ISSUE TITLE
0.1.18 issues training SoundStream

### ISSUE THREAD

**Issue by djqualia** [lucidrains/audiolm-pytorch#35]
Since the latest version, I'm getting an error training sound stream: AttributeError: 'tuple' object has no attribute 'to'

A more complete stack trace:

Traceback (most recent call last):
  File "train_soundstream.py", line 20, in <module>
    trainer.train()
  File "/mnt/c/audio-ml-workspace/audiolm/audiolm_pytorch/trainer.py", line 376, in train
    logs = self.train_step()
  File "/mnt/c/audio-ml-workspace/audiolm/audiolm_pytorch/trainer.py", line 271, in train_step
    wave = wave.to(device)
AttributeError: 'tuple' object has no attribute 'to'

I'll see if I can figure out what caused this...

**Comment by lucidrains** [comment]
@djqualia this is my fault too, for trying to introduce some magic to make text conditioned training easier

should be fixed!

**Comment by djqualia** [comment]
Yes that worked thanks!
