### ISSUE TITLE
Error training soundstream in 0.3.0

### ISSUE THREAD

**Issue by djqualia** [lucidrains/audiolm-pytorch#42]
Since the latest code (0.3.0) I get the following error attempting to train a SoundStream:

Traceback (most recent call last):
  File "train_soundstream.py", line 26, in <module>
    trainer.train()
  File "/home/qualia/code/audiolm/audiolm_pytorch/trainer.py", line 402, in train
    logs = self.train_step()
  File "/home/qualia/code/audiolm/audiolm_pytorch/trainer.py", line 320, in train_step
    discr_losses = self.soundstream(
  File "/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 416, in forward
    stft_discr_loss = (hinge_discr_loss(stft_fake_logits.real, stft_real_logits.real) + hinge_discr_loss(stft_fake_logits.imag, stft_real_logits.imag)) / 2
RuntimeError: imag is not implemented for tensors with non-complex dtypes.

**Comment by lucidrains** [comment]
@djqualia oh oops, i broke it haha https://github.com/lucidrains/audiolm-pytorch/commit/c5ea46186fbe77538003e363c4fbb3dc0dfe9076 should be distributed friendly now btw!

**Comment by djqualia** [comment]
Unfortunately, now I'm getting a different error:

  File "train_soundstream.py", line 26, in <module>
    trainer.train()
  File "/home/qualia/code/audiolm/audiolm_pytorch/trainer.py", line 411, in train
    logs = self.train_step()
  File "/home/qualia/code/audiolm/audiolm_pytorch/trainer.py", line 324, in train_step
    discr_losses = self.soundstream(
  File "/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 419, in forward
    stft_grad_penalty = gradient_penalty(real, stft_discr_loss)
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 41, in gradient_penalty
    gradients = torch_grad(
  File "/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

**Comment by lucidrains** [comment]
@djqualia :man_facepalming: my bad, want to try 0.3.2 ?

**Comment by djqualia** [comment]
That worked, thanks!
