### ISSUE TITLE
Global num_workers?

### ISSUE THREAD

**Issue by turian** [lucidrains/audiolm-pytorch#56]
In training SoundStream, I see that there is no way (besides modifying code) to set the num_workers.

But doing so has a dramatic impact on speed on the machine I'm trying right now. A way to set this globally, or for each trainer, would be nice.

BTW, I set num_workers=32 and after some steps it gets this error:

```
Traceback (most recent call last):
  File "/root/./foo.py", line 21, in <module>
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/audiolm_pytorch/trainer.py", line 411, in train
    logs = self.train_step()
  File "/opt/conda/lib/python3.10/site-packages/audiolm_pytorch/trainer.py", line 302, in train_step
    wave, = next(self.dl_iter)
  File "/opt/conda/lib/python3.10/site-packages/audiolm_pytorch/trainer.py", line 70, in cycle
    for data in dl:
  File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 383, in __iter__
    next_batch = next(dataloader_iter)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 13.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 295, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/opt/conda/lib/python3.10/site-packages/audiolm_pytorch/data.py", line 74, in __getitem__
    data_tuple = tuple((resample(d, sample_hz, target_sample_hz) if exists(target_sample_hz) else d) for d, target_sample_hz in zip(data, self.target_sample_hz))
  File "/opt/conda/lib/python3.10/site-packages/audiolm_pytorch/data.py", line 74, in <genexpr>
    data_tuple = tuple((resample(d, sample_hz, target_sample_hz) if exists(target_sample_hz) else d) for d, target_sample_hz in zip(data, self.target_sample_hz))
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 1600, in resample
    resampled = _apply_sinc_resample_kernel(waveform, orig_freq, new_freq, gcd, kernel, width)
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 1532, in _apply_sinc_resample_kernel
    waveform = waveform.view(-1, shape[-1])
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by turian** [comment]
@lucidrains Okay so these are empty files.

I have a corpus of audio where some are really long, and rather than wasting a lot of time on `torchaudio.load`, I used ffmpeg to chop it into 10 second clips. But many of them are empty.

It would be nice if your code could handle this, or at least throw an informative error, but I understand that this complaint is essentially user error.

**Comment by lucidrains** [comment]
@turian ok, yea, let's try [0.4.8](https://github.com/lucidrains/audiolm-pytorch/commit/153911830a9f444ed506c02982e478fb64925595)
