### ISSUE TITLE
Error training soundstream on 0.12.1

### ISSUE THREAD

**Issue by djqualia** [lucidrains/audiolm-pytorch#88]
Traceback (most recent call last):
  File "train_soundstream.py", line 6, in <module>
    soundstream = config_util.createSoundStream(config)
  File "/home/qualia/code/audiolm/config_util.py", line 28, in createSoundStream
    soundstream = SoundStream(
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 411, in __init__
    self.encoder_attn = nn.Sequential(*[LocalTransformerBlock(**attn_kwargs) for _ in range(attn_depth)]) if use_local_attn else None
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 411, in <listcomp>
    self.encoder_attn = nn.Sequential(*[LocalTransformerBlock(**attn_kwargs) for _ in range(attn_depth)]) if use_local_attn else None
  File "/home/qualia/code/audiolm/audiolm_pytorch/soundstream.py", line 333, in __init__
    self.attn = LocalMHA(dim = dim, qk_rmsnorm = True, **kwargs)
  File "/home/qualia/anaconda3/envs/audiolm/lib/python3.8/site-packages/local_attention/transformer.py", line 55, in __init__
    self.attn_fn = LocalAttention(
TypeError: __init__() got an unexpected keyword argument 'qk_rmsnorm'

Any suggestion for how to fix?  Do I have an old version of some dependency?

**Comment by lucidrains** [comment]
@djqualia oh weird, I enforced it in setup.py for local-attention to be 1.6.0 or above (added a new attention stabilization trick)

**Comment by lucidrains** [comment]
try doing a `pip install local-attention -U`

**Comment by djqualia** [comment]
ah, my bad, should have thought to re-run setup (i've been overwriting the same code for a while now).  thanks!
